require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LeaveConflictsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # LeaveConflict. As you add validations to LeaveConflict, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LeaveConflictsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all leave_conflicts as @leave_conflicts" do
      leave_conflict = LeaveConflict.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:leave_conflicts)).to eq([leave_conflict])
    end
  end

  describe "GET #show" do
    it "assigns the requested leave_conflict as @leave_conflict" do
      leave_conflict = LeaveConflict.create! valid_attributes
      get :show, {:id => leave_conflict.to_param}, valid_session
      expect(assigns(:leave_conflict)).to eq(leave_conflict)
    end
  end

  describe "GET #new" do
    it "assigns a new leave_conflict as @leave_conflict" do
      get :new, {}, valid_session
      expect(assigns(:leave_conflict)).to be_a_new(LeaveConflict)
    end
  end

  describe "GET #edit" do
    it "assigns the requested leave_conflict as @leave_conflict" do
      leave_conflict = LeaveConflict.create! valid_attributes
      get :edit, {:id => leave_conflict.to_param}, valid_session
      expect(assigns(:leave_conflict)).to eq(leave_conflict)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new LeaveConflict" do
        expect {
          post :create, {:leave_conflict => valid_attributes}, valid_session
        }.to change(LeaveConflict, :count).by(1)
      end

      it "assigns a newly created leave_conflict as @leave_conflict" do
        post :create, {:leave_conflict => valid_attributes}, valid_session
        expect(assigns(:leave_conflict)).to be_a(LeaveConflict)
        expect(assigns(:leave_conflict)).to be_persisted
      end

      it "redirects to the created leave_conflict" do
        post :create, {:leave_conflict => valid_attributes}, valid_session
        expect(response).to redirect_to(LeaveConflict.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved leave_conflict as @leave_conflict" do
        post :create, {:leave_conflict => invalid_attributes}, valid_session
        expect(assigns(:leave_conflict)).to be_a_new(LeaveConflict)
      end

      it "re-renders the 'new' template" do
        post :create, {:leave_conflict => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested leave_conflict" do
        leave_conflict = LeaveConflict.create! valid_attributes
        put :update, {:id => leave_conflict.to_param, :leave_conflict => new_attributes}, valid_session
        leave_conflict.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested leave_conflict as @leave_conflict" do
        leave_conflict = LeaveConflict.create! valid_attributes
        put :update, {:id => leave_conflict.to_param, :leave_conflict => valid_attributes}, valid_session
        expect(assigns(:leave_conflict)).to eq(leave_conflict)
      end

      it "redirects to the leave_conflict" do
        leave_conflict = LeaveConflict.create! valid_attributes
        put :update, {:id => leave_conflict.to_param, :leave_conflict => valid_attributes}, valid_session
        expect(response).to redirect_to(leave_conflict)
      end
    end

    context "with invalid params" do
      it "assigns the leave_conflict as @leave_conflict" do
        leave_conflict = LeaveConflict.create! valid_attributes
        put :update, {:id => leave_conflict.to_param, :leave_conflict => invalid_attributes}, valid_session
        expect(assigns(:leave_conflict)).to eq(leave_conflict)
      end

      it "re-renders the 'edit' template" do
        leave_conflict = LeaveConflict.create! valid_attributes
        put :update, {:id => leave_conflict.to_param, :leave_conflict => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested leave_conflict" do
      leave_conflict = LeaveConflict.create! valid_attributes
      expect {
        delete :destroy, {:id => leave_conflict.to_param}, valid_session
      }.to change(LeaveConflict, :count).by(-1)
    end

    it "redirects to the leave_conflicts list" do
      leave_conflict = LeaveConflict.create! valid_attributes
      delete :destroy, {:id => leave_conflict.to_param}, valid_session
      expect(response).to redirect_to(leave_conflicts_url)
    end
  end

end
